### ISSUE TITLE
针对orm，官网给出了databases的异步解决方案

### ISSUE THREAD

**Issue by findre** [CoderCharm/FastAdmin#4]
您在项目里没有尝试databases是为什么呢？databases有什么坑吗？还是这个方案不够优雅😂

**Comment by wxy2077** [comment]
额，并不是，正如我README.md开头所说，我这个只是练习的Demo，并没有用上生产，而且我这个项目没写完，因为我感觉后台项目全是表格的CURD。(我也不知道为何有20多个老哥点star🤪)

https://fastapi.tiangolo.com/advanced/async-sql-databases/  至于这个异步的方案，我当时文档也没细看，我是根据作者给的全栈项目生成工具 https://github.com/tiangolo/full-stack-fastapi-postgresql 参考的，有些地方自己修修改改，改成自己用起来比较合适的。

**Comment by findre** [comment]
了解了，
