### ISSUE TITLE
views中的分页、token写到基类里更好，这样不用每次都写到views上

### ISSUE THREAD

**Issue by douyahu** [CoderCharm/FastAdmin#5]
![image](https://user-images.githubusercontent.com/47881587/94667511-7f64c480-0341-11eb-8448-0c38c4ab0404.png)
![image](https://user-images.githubusercontent.com/47881587/94667551-8ab7f000-0341-11eb-933f-1e405c4f475b.png)
![image](https://user-images.githubusercontent.com/47881587/94667568-90153a80-0341-11eb-8d5c-0ec2164933b0.png)
![image](https://user-images.githubusercontent.com/47881587/94667579-94415800-0341-11eb-8bfb-9c90946b1aa2.png)

**Comment by douyahu** [comment]
token的话，建议使用session对象，第一次登陆后将token写入到session里
![image](https://user-images.githubusercontent.com/47881587/94668031-221d4300-0342-11eb-9302-2dd694c5d265.png)
![image](https://user-images.githubusercontent.com/47881587/94668132-437e2f00-0342-11eb-9eac-1c61cfe8dd73.png)

**Comment by wxy2077** [comment]
感觉老哥的建议，分页这个做法很棒。token我之前是想放到分组路由里面去验证应该更简洁些，参考https://fastapi.tiangolo.com/tutorial/bigger-applications/#import-fastapi
